/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const DEFAULT_LANG: typeof import('./lib/constants')['DEFAULT_LANG']
  const DEFAULT_THEME: typeof import('./lib/constants')['DEFAULT_THEME']
  const LANGS: typeof import('./lib/constants')['LANGS']
  const RTL_LANGS: typeof import('./lib/constants')['RTL_LANGS']
  const THEMES: typeof import('./lib/constants')['THEMES']
  const afterUpdate: typeof import('svelte')['afterUpdate']
  const beforeUpdate: typeof import('svelte')['beforeUpdate']
  const blur: typeof import('svelte/transition')['blur']
  const createEventDispatcher: typeof import('svelte')['createEventDispatcher']
  const crossfade: typeof import('svelte/transition')['crossfade']
  const derived: typeof import('svelte/store')['derived']
  const dir_toggle: typeof import('./lib/utils')['dir_toggle']
  const draw: typeof import('svelte/transition')['draw']
  const fade: typeof import('svelte/transition')['fade']
  const fly: typeof import('svelte/transition')['fly']
  const get: typeof import('svelte/store')['get']
  const getAllContexts: typeof import('svelte')['getAllContexts']
  const getContext: typeof import('svelte')['getContext']
  const hasContext: typeof import('svelte')['hasContext']
  const lang_toggle: typeof import('./lib/utils')['lang_toggle']
  const onDestroy: typeof import('svelte')['onDestroy']
  const onMount: typeof import('svelte')['onMount']
  const readable: typeof import('svelte/store')['readable']
  const scale: typeof import('svelte/transition')['scale']
  const setContext: typeof import('svelte')['setContext']
  const slide: typeof import('svelte/transition')['slide']
  const theme_toggle: typeof import('./lib/utils')['theme_toggle']
  const tick: typeof import('svelte')['tick']
  const writable: typeof import('svelte/store')['writable']
}
