// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const AccordionMulti: typeof import("./components/accordion/multi.svelte")["default"]
    const AccordionSingle: typeof import("./components/accordion/single.svelte")["default"]
    const Nav: typeof import("./components/nav.svelte")["default"]
}

export {}
